version: '3.8'
services:
  n8n:
    image: n8nio/n8n:latest
    container_name: n8n
    restart: unless-stopped
    ports:
      - "5678:5678"
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=TU_USUARIO
      - N8N_BASIC_AUTH_PASSWORD=TU_PASSWORD
      - GENERIC_TIMEZONE=Europe/Madrid
    volumes:
      - ./n8n_data:/home/node/.n8n

    deploy:
      resources:
        limits:
          cpus: '1.5'   # Máximo 1.5 CPU
          memory: 1G    # Máximo 1 GB RAM
        reservations:
          cpus: '0.5'   # Reserva mínima
          memory: 512M  # Reserva mínima
